import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "David Pescariu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={workSans.className}>
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
